### ISSUE TITLE
Stripping blocks in Docxtpl

### ISSUE THREAD

**Issue by pablosolar** [elapouya/python-docx-template#133]
Hello @elapouya 

Im trying to generate some entries of a dict in the template this way:
```
Title
{% for a in primary_biblio_data %}
      {{ a[1] }}.   {{ a[0] }}
{% endfor %}
```
Problem is that is being generated this way:

```
Title

      1.   A

      2.   B

      3.   C
```

What I want is an output like:

```
Title

      1.   A
      2.   B
      3.   C
```

According to Jinja2 doc, I've tried all the stripping options like:

```
{% for a in primary_biblio_data %}
      {{ a[1] }}.   {{ a[0] }}
{%- endfor %}
```
or

```
{% for a in primary_biblio_data -%}
      {{ a[1] }}.   {{ a[0] }}
{% endfor %}
```
But it only works if I define the block this way:
```
{% for a in primary_biblio_data %}
      {{ a[1] }}.   {{ a[0] }} {% endfor %}
```
this makes the template less readable. Stripping doest not work for docxtpl or am I doing something wrong?

Thank you in advance!

**Comment by elapouya** [comment]
try {%p  instead of {%
see documentation

Le 1 août 2018 17:28, "pablosolar" <notifications@github.com> a écrit :

Hello @elapouya <https://github.com/elapouya>

Im trying to generate some entries of a dict in the template this way:

Title
{% for a in primary_biblio_data %}
      {{ a[1] }}.   {{ a[0] }}
{% endfor %}

Problem is that is being generated this way:

Title

      1.   A

      2.   B

      3.   C

What I want is an output like:

Title

      1.   A
      2.   B
      3.   C

According to Jinja2 doc, I've tried all the stripping options like:

{% for a in primary_biblio_data %}
      {{ a[1] }}.   {{ a[0] }}
{%- endfor %}

or

{% for a in primary_biblio_data -%}
      {{ a[1] }}.   {{ a[0] }}
{% endfor %}

But it only works if I define the block this way:

{% for a in primary_biblio_data %}
      {{ a[1] }}.   {{ a[0] }} {% endfor %}

this makes the template less readable. Stripping doest not work for docxtpl
or am I doing something wrong?

Thank you in advance!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/elapouya/python-docx-template/issues/133>, or mute the
thread
