### ISSUE TITLE
DocxTemplate method fix_tables: AttributeError: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by llazzaro** [elapouya/python-docx-template#176]
The problem is the following line at file lib/python2.7/site-packages/docxtpl/__init__.py +330

```
grid_span = tc_pr is not None and tc_pr.find(ns + 'gridSpan') 
```

grid_span is False after the execution of the previous line.

I think we need to change the next line:

```
if grid_span is not None:
```

to 

```
if grid_span:
```

I could create a pull request and will try to make an unit test

```
 Traceback (most recent call last):
  File "/home/lcubo/workspace/faraday/server/utils/executive_reports.py", line 95, in create_report
    hosts, services)
  File "/home/lcubo/workspace/faraday/reports/executive/generic_report.py", line 330, in create_document
    tpl.render(context, jinja_env)
  File "/home/lcubo/.pyenv/versions/faraday4/lib/python2.7/site-packages/docxtpl/__init__.py", line 264, in render
    tree = self.fix_tables(xml_src)
  File "/home/lcubo/.pyenv/versions/faraday4/lib/python2.7/site-packages/docxtpl/__init__.py", line 338, in fix_tables
    cells_len = functools.reduce(get_cell_len, cells, 0)
  File "/home/lcubo/.pyenv/versions/faraday4/lib/python2.7/site-packages/docxtpl/__init__.py", line 331, in get_cell_len
    return total + int(grid_span.get(ns + 'val'))
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by mx2048** [comment]
To begin with, I would mention the original author of the code @nickgashkov from pull request #164

**Comment by nickgashkov** [comment]
Hello there!

My bad, I've entangled in checks. This guard should be rewritten, but `if grid_span` won't do the trick.

The problem is that a XML tag with an empty body is considered false-ish regardless of it's attributes (see `xml.etree.ElementTree.Element#__bool__`). And the 'gridSpan' always has an empty body with a `val` attribute (see http://officeopenxml.com/WPtableGrid.php).

So, it's better to set `grid_span` to `None` if `tc_pr` is `None` also. Something like:
```python
grid_span = None if tc_pr is None else tc_pr.find(ns + 'gridSpan')
```

It'd be great if you could work on the PR, or, I can do it myself later today.

**Comment by llazzaro** [comment]
Hi!
This fixed the issue, thanks a lot!
are you expecting to release a new version?

**Comment by elapouya** [comment]
Done : v0.5.18
