### ISSUE TITLE
DocxTemplate support file-like argument

### ISSUE THREAD

**Issue by dawncold** [elapouya/python-docx-template#182]
I use a file-like argument for `DocxTemplate`, and it works fine for me, but I found the last invocation of `save` is `post_processing` which expects a String file name instead of a file-like stream.

**Comment by elapouya** [comment]
Hello,

This is due to the fact that the post_precessing manage a zipfile object
that is not just a file-like stream.

One way to do what you want is to generate the final docx file and then to
reread it and inject it into your file-like stream : quite ugly.
Another way if you do not need pre/post processing (used when you need to
replace pictures) is to call directly your_template.docx.save() instead of
your_template.save()

**Comment by edufresne** [comment]
This should be possible now as of release 0.6.2

**Comment by elapouya** [comment]
Yes, now supported in latest version
