### ISSUE TITLE
Question: can you render the outputs multiple times?

### ISSUE THREAD

**Issue by Hoffelhas** [elapouya/python-docx-template#220]
Hello,

After rendering your template, I seem to lose all the variables in that output. Is it possible to render that output again? Example:

Step 1:
doc = DocxTemplate("my_word_template.docx")
context = { 'company_name' : "World company 1" }
doc.render(context)
doc.save("generated_doc1.docx")

Step 2:
doc = DocxTemplate("generated_doc1.docx")
context = { 'company_name' : "World company 2" }
doc.render(context)
doc.save("generated_doc2.docx")

Thanks.

**Comment by elapouya** [comment]
Why do you want to generate a template?

**Comment by Hoffelhas** [comment]
I have a standard report to present certain calculation data. I want to use the initial template to add this data, but I always have to add some custom explanations in the report. Often at the end of the process a slight modification to the calculation has to be made, so I want to re-update the data.

So there's the issue: if I use the original template I have to manually add all custom explanations again. And with the first rendered output, I have no jinja2 variables anymore. This is why I'm wondering if it's possible to keep rendering the file you're working on.

**Comment by elapouya** [comment]
Use only the first template in your two steps rendering :
On the 2nd step, give again the same data and the new explanations

If the problem comes from you do not have access anymore to data at the 2nd
step, you can postpone explanations rendering in 2nd step by using {_{ and
}_} syntax in your first template (see documentation). But by no way you
can rerender an explanation that has been already rendered, simply because
all {{}} does not exist anymore after the first rendering.

Understand that - usually - docxtpl is used to generate final documents
that is not to be rendered later.
