### ISSUE TITLE
Generation of corrupted docx when there are tables in subdoc

### ISSUE THREAD

**Issue by rohantalesara** [elapouya/python-docx-template#239]
Hi @elapouya ,
First of all this is a great library and has really helped us do our project with ease.

We're currently facing a problem, where we have a table in a sub-template, which we render in our main template as a subdoc. However, the generated docx is corrupted, and we are unable to open without using Word's recovery.

We compared the xml of both the corrupt and recovered docx files, and there seems to be an issue in the w:p tags in the table, where the corrupted xml doesn't have paraId and textId, while the recovered doc has them.

Corrupted:
![image](https://user-images.githubusercontent.com/31321664/70391463-9bd2f180-19fb-11ea-8e0a-50b27bfa53e6.png)

Recovered:
![image](https://user-images.githubusercontent.com/31321664/70391468-a9887700-19fb-11ea-9fe4-b0bf5a1a35dd.png)

Here are the [main template](https://drive.google.com/file/d/1Dvpsn09K7Kt_EeT-ahZ2no3V8G4z1dah/view?usp=sharing) and the [sub-template](https://drive.google.com/file/d/1JaABkGi9tMQZmDOfBG_fY_yRuch4cITN/view?usp=sharing) (containing the table).

And the corrupted and recovered xml files attached too.
[corrupt1.txt](https://github.com/elapouya/python-docx-template/files/3936470/corrupt1.txt)
[recovered1.txt](https://github.com/elapouya/python-docx-template/files/3936471/recovered1.txt)

**Comment by elapouya** [comment]
HI,

docxtpl's subdocuments are quite experimental,
you have to know that it inheritates all styles from the main document.
So if you have different word environments (styles, parameters etc...), you
may experience some trouble when having a subdocument.
May be, you can build your sub-template from the main template (load the
main template, erase everything, and build your sub-template from this
empty page)
Note that, as you are using {{ }} in your templates, all the docx
generation that is related to your problem is done by python-docx and not
python-docx-template (except the inherit thing I spoke above).

Le dim. 8 déc. 2019 à 16:27, Rohan Talesara <notifications@github.com> a
écrit :
