### ISSUE TITLE
Text deleted by {%- and -%} merging feature

### ISSUE THREAD

**Issue by markdoliner** [elapouya/python-docx-template#272]
Hi there! I believe I'm seeing a bug in the new `{%-` `-%}` merging feature introduced in version 0.9.0 (references: [commit](https://github.com/elapouya/python-docx-template/commit/97be69b950830188435b22d07b0c218cafd026c7), [documentation](https://docxtpl.readthedocs.io/en/latest/#split-and-merge-text)) where some document text is being deleted. It's very strange. It seems to happen sometimes when there is a non-whitespace character immediately before or immediately after the `{%-` or `-%}` tag. But it doesn't always happen. See the attached document, where there are two identical sequences of text, one where the problem happens and another where it doesn't. It seems like it must depend on some unseen structure of the document. Or possibly there _is_ some subtle difference between the two sequences that I'm overlooking.

In any case, I wouldn't expect the merging feature to ever delete non-whitespace. Is this the expected behavior?

### Screenshot of the template docx
![Screen Shot 2020-04-28 at 10 42 16 AM](https://user-images.githubusercontent.com/225813/80503367-c0465080-893f-11ea-9cbf-93ed1af6e969.png)

### Screenshot of the rendered docx
![Screen Shot 2020-04-28 at 10 42 34 AM](https://user-images.githubusercontent.com/225813/80503380-c3d9d780-893f-11ea-9305-4c6ffabae238.png)

### The template docx
[merge_paragraph_should_only_delete_whitespace.docx](https://github.com/elapouya/python-docx-template/files/4546662/merge_paragraph_should_only_delete_whitespace.docx)

### The rendered docx
[rendered_output_from_v0.9.2.docx](https://github.com/elapouya/python-docx-template/files/4546663/rendered_output_from_v0.9.2.docx)

**Comment by elapouya** [comment]
This is not a bug, the {%- -%} must be alone on a line, see example in the doc

**Comment by mdoliner-st** [comment]
Ah I see. I had seen the example. I guess it wasn't obvious to me that {%- -%} must be alone on a line. Maybe because I'm used to Jinja's behavior regarding {%- -%}, where it collapses all whitespace and doesn't have the same requirement about being alone on a line. (Described in the middle of [this section](https://jinja.palletsprojects.com/en/2.11.x/templates/#whitespace-control), "If you add a minus sign.")

I wonder if it would be worth mentioning this requirement in the documentation?

I might also suggest having the render() function validate that {%- -%} is alone on a line and log a warning or raise an exception otherwise, since the behavior might be surprising or undesirable to some. But I understand that this is certainly open to opinion on how it should be handled, and I have no idea how feasible it is do add this check.

In any case I'll leave it in your hands. Thanks for your help!

**Comment by markdoliner** [comment]
Ah I see. I had seen the example. I guess it wasn't obvious to me that {%- -%} must be alone on a line. Maybe because I'm used to Jinja's behavior regarding {%- -%}, where it collapses all whitespace and doesn't have the same requirement about being alone on a line. (Described in the middle of [this section](https://jinja.palletsprojects.com/en/2.11.x/templates/#whitespace-control), "If you add a minus sign.")

I wonder if it would be worth mentioning this requirement in the documentation?

I might also suggest having the render() function validate that {%- -%} is alone on a line and log a warning or raise an exception otherwise, since the behavior might be surprising or undesirable to some. But I understand that this is certainly open to opinion on how it should be handled, and I have no idea how feasible it is do add this check.

In any case I'll leave it in your hands. Thanks for your help!

**Comment by elapouya** [comment]
I will put a note in the documentation
