### ISSUE TITLE
How to check a checkbox control within a docx template?

### ISSUE THREAD

**Issue by anazimokcp** [elapouya/python-docx-template#310]
I have a fairly large document with a large number of checkboxes, is there a way to check the checkbox based on the specified condition? Please see the attached screenshot.

<img width="767" alt="Screen Shot 2020-10-11 at 11 41 53 AM" src="https://user-images.githubusercontent.com/63605620/95683054-e6db0980-0bb6-11eb-93b0-e5d0b4724c86.png">

**Comment by elapouya** [comment]
Unfortunately it is not possible to manipulate checkboxes
You can only do something textual like this : 
```[{% if implemented %}X{% else %}  {% endif %}] Implemented ```

**Comment by Michae94** [comment]
I would just wrap the checkbox instead:
![image](https://user-images.githubusercontent.com/45620222/96715681-3e8e2780-13a4-11eb-8a00-928a86f6cc53.png)

**Comment by karolzlot** [comment]
Related to #270 

----
If somebody would like to implement this one day:

In theory it could be implemented using approach similar to https://github.com/iulica/docx-mailmerge

Benefit is that if would take less space and make template more readable. Not sure if it is worth it because above approaches work well.
