### ISSUE TITLE
[QUESTION] Is there a way to insert whole documents into the jinja tags? 

### ISSUE THREAD

**Issue by ZsoltKralik** [elapouya/python-docx-template#324]
Hi, I'm trying to insert another docx (with pictures, tables) to the template. I've read the documentation and the sub-document section, but I was unable to resolve this issue. With the sub-doc I was able to put the full document to the template, however when I open it up with Microsoft word it shows that the picture cannot be displayed and the tables are messed up. Please point me to the right direction, much appreciated. 
Thank you.

**Comment by elapouya** [comment]
Document merging is very limited with docxtpl. The reason is that pictures, tables, styles etc... are managed in other xml files than the main document. There is no plan to do what you want in the future.
Another solution may be to embed your docx, but you will have to click on it to open : see tests/embedded.py
Otherwise, the only solution is to build a template that is already merged with your external docx.
But if your goal is to dynamically merge some docx, it is very limited, you have to use subdoc like you did and cross your figers...

**Comment by ZsoltKralik** [comment]
Thank you @elapouya Eric Lapouyade. Other option was that I've considered is to put an xml tag or any marking into the template and somehow copy the desired document there. My programming knowledge/experience is little, that is a limiting factor as well. Everything I've searched for points back to you and this repo.

**Comment by elapouya** [comment]
See #321

**Comment by ZsoltKralik** [comment]
Hi @elapouya, #321 was opened by my boss. However I was able to find a solution. 
It is easy to do it with document merging (with docxcompose library). I just had to slice the template and merge it multiple times. I was able to extract the wanted part with deleting everything apart from the wanted piece then merge it with the template. Sharing this as maybe it could be helpful for someone or worth considering. Thank you for your previous inputs.
