### ISSUE TITLE
Image in footer

### ISSUE THREAD

**Issue by dunix15** [elapouya/python-docx-template#51]
Unfortunately I cannot add image in the footer.
Some example files: (python script with extension .txt)

![python_logo](https://cloud.githubusercontent.com/assets/5971876/18080076/1bffccd2-6e94-11e6-87d0-c041fbe3c263.png)
[footer_tpl.docx](https://github.com/elapouya/python-docx-template/files/444242/footer_tpl.docx)
[footer.docx](https://github.com/elapouya/python-docx-template/files/444241/footer.docx)
[img_in_footer.txt](https://github.com/elapouya/python-docx-template/files/444243/img_in_footer.txt)

**Comment by elapouya** [comment]
I added direct support for images in docxtpl 0.3.0 : please have a try : no need to use subdoc anymore.

**Comment by dunix15** [comment]
Nice, but even new approach doesn't work in header and footer.

**Comment by antetna** [comment]
I have same problem with header too. Looks like that file created from template has no r:embed attribute 

it creates this 

` <pic:blipFill>
<a:blip/>
<a:stretch>
<a:fillRect/>
</a:stretch>
</pic:blipFill>`

but it should be something like this

`<pic:blipFill>
<a:blip r:embed="rId1"/>
<a:stretch>
<a:fillRect/>
</a:stretch>
</pic:blipFill>`

if you manually edit docx image will appear :)

**Comment by elapouya** [comment]
Did you tried InlineImage new feature ?

2017-06-30 14:23 GMT+02:00 antetna <notifications@github.com>:

**Comment by cameronfrazier** [comment]
Hi @elapouya,

You have a really helpful package here, and I hope I can help improve it. I use it alot for automation of my reporting and appreciate all the work you've put into it.

I'm having the same issue as @antetna, only with the new InlineImage object. Examples are attached.

I updated the previous sample code to use InlineImage, and then manually fixed the rendered docx (right-click -> change image), and finally compared the files and structure of the two documents. I noticed that when rendered the _root/word/\_rels_ folder was missing the _footer2.xml.rels_ and _header2.xml.rels_ documents. Additionally, the `<a:blip r:embed="rIdXX" />` element was using the reference referred to in the _document.xml.rels_ file, leading to the image failing to be shown.

Demonstrating that this is the issue, I manually added the missing rels files and updated the footer2 and header2 files. Doing this corrected the issue.

I don't know how to update your code to resolve this, but I hope I can speed up your work when you have the time to work on it. 

Attached files:
Template: [header_footer_image_test.docx](https://github.com/elapouya/python-docx-template/files/1233087/header_footer_image_test.docx)
Render Code: [header_footer_image_test.py.txt](https://github.com/elapouya/python-docx-template/files/1233088/header_footer_image_test.py.txt)  [based on @antetna's ]
As Rendered: [header_footer_image_test_render.docx](https://github.com/elapouya/python-docx-template/files/1233089/header_footer_image_test_render.docx)
Fixed in Word: [header_footer_image_test_render_fixed_in_Word.docx](https://github.com/elapouya/python-docx-template/files/1233120/header_footer_image_test_render_fixed_in_Word.docx)
Corrected Rels: [header_footer_image_test_render_with_rels.docx](https://github.com/elapouya/python-docx-template/files/1233123/header_footer_image_test_render_with_rels.docx)
Source Image: [python.png](https://user-images.githubusercontent.com/7953204/29441370-ce84f1e8-8405-11e7-8d36-51771636948f.png)

**Comment by elapouya** [comment]
I found another strategy to have dynamic images in header/footer. The
problem was that python-docx does not support adding header/footer images.
So the procedure I propose is to have a template having dummy image at
header/footer, ready to be replaced by the new utility :

replace_medias()

Have a look to the demo : tests/header_footer_image.py

This is available at the latest github revision.

Tell me if it works for you.

2017-08-18 4:39 GMT+02:00 cameronfrazier <notifications@github.com>:
