### ISSUE TITLE
Not able to apply the same style twice

### ISSUE THREAD

**Issue by bartsowka** [elapouya/python-docx-template#75]
`"text8" : RichText("text8: ",style="style2")`

This code should apply style2 onto text8. (style2 is just bold 14pt Arial).

However, this is the result: https://i.gyazo.com/911204151bc1e5c1e5f95e2ce20d7288.png

When I first applied style2, everything worked.

Basically, texts 1-8 exist. texts 2,4,6 should have had style2 on them, when I tried to do it individually only the first one was working. They only worked when I applied it in a loop. This is what I assume is happening with this.

**Comment by elapouya** [comment]
Please provide python code and docx template you used

**Comment by bartsowka** [comment]
I'm tempted to declare this solved but something weird is going on.

The program now works, but only when the {{r text8 }} already has style2 applied to it. (I assumed it was applied since it was the exact same, just wasn't technically style2).

Either I wasn't aware that this was the case, or this is a bug.

The code: `from docxtpl import DocxTemplate, RichText

doc = DocxTemplate("rd.docx")
context = { "text1" : RichText("text 1 here", style="style1"),
            "texts1": [
                {"upper": RichText("text 2 here",style="style2"), "lower": RichText("text 3 here",style="style3")},
                {"upper": RichText("text 4 here",style="style2"), "lower": RichText("text 5 here",style="style3")},
                {"upper": RichText("text 6 here",style="style2"), "lower": RichText("text 7 here",style="style3")}
                ],
            "text8" : RichText("text8",style="style2")
            }
doc.render(context)
doc.save("generated_doc.docx")`

The docx has sensitive information to my understanding but here is a screenshot of the area of interest: https://i.gyazo.com/72e8d0ed9a2aa94a1c762413270c6905.png

**Comment by elapouya** [comment]
Please, do a minimal template so I can test it
Screenshots are useless for me

**Comment by bartsowka** [comment]
[teeest.docx](https://github.com/elapouya/python-docx-template/files/836595/teeest.docx)
In this example, text8 works and text9 doesn't

**Comment by ericdupo** [comment]
I found the root cause : 
Actually, "style2" is a Paragraph Style name, RichText uses Charater Style name.
So when doing RichText(...,style="style2") do ... nothing !
It works in the loop because you set the style2/style3 as paragraph style (upper and lower lines are paragraph, styles are duplicated by the loop itself)
For text8, if you look carefully in the docx : there is no paragraph style, but a Caracter Style ("Style2 Char") : that is the reason why it appears bold in the template but not in the generated doc.

So the solution is :  Create you own **CHARACTER** STYLE (without space in the name for compatibility reason)
It is important to create your own style because predefined ones may have other internal name.

**Comment by bartsowka** [comment]
Thanks for your help @ericdupo
