### ISSUE TITLE
Some features can not be used on Office2016

### ISSUE THREAD

**Issue by jamcplusplus** [elapouya/python-docx-template#78]
I tried to use word2016 as template, but there is a bug. If I used the for loop in Jinja2, docxtpl cannot work well. But the same Jinja2 in word2013, it works well.

**Comment by elapouya** [comment]
Is it possible to choose output docx format version in word 2016 ?

Le 19 mai 2017 04:33, "jamcplusplus" <notifications@github.com> a écrit :

I tried to use word2016 as template, but there is a bug. If I used the for
loop in Jinja2, docxtpl cannot work well. But the same Jinja2 in word2013,
it works well.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/elapouya/python-docx-template/issues/78>, or mute the
thread

**Comment by jamcplusplus** [comment]
I'll give you feedback next week~

**Comment by elapouya** [comment]
No feedback : closing
